language: bash
services: docker
env:
  matrix:
    - VERSION=9.3 VARIANT=alpine
install:
  - git clone https://github.com/evaneos/docker-postgis.git ~/docker-postgis
before_script:
  - env | sort
  - cd "$VERSION"
  - export image="evaneos/postgis:${VERSION}${VARIANT:+-${VARIANT}}"
script:
  - docker build -t "$image" .
after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $image;
    fi
